upload_pack_by_branch: Replace deepen with deepen_level
larshp/abapGit pull request #3835
Opened 2020-09-03 13:40 UTC by mariusraht2

Related to #3040

We need a new method upload_pack_by_commit which shares ~90% of it's source code with upload_pack_by_branch but needs a specifiable deepen_level import parameter. So this PR makes sure we can merge redundant and duplicate source code for these two methods into a new upload_pack method (will be introduced after merging this).

2020-09-03 14:42 UTC, larshp commented on src/git/zcl_abapgit_git_transport.clas.abap
> +    TYPES: ty_deepen_level TYPE n LENGTH 2.
suggest being able to pass any number, there is no need to add restrictions(eg. passing 100 as deepen level wont work), or adding extra TYPES

2020-09-03 18:30 UTC, mbtools commented
128 commits for this change? but looks like you got what you wanted in the end

2020-09-03 18:33 UTC, mariusraht2 commented
:D No, that are just the ones I merged from master into my related branch

2020-09-04 10:26 UTC, flaiker commented
Then only submit the three changes? Lars will probably squash anyway but the process for updating your fork seems off.

2020-09-04 10:37 UTC, mariusraht2 commented
What would be the best way to update my fork? I do it by creating a PR for my master branch with the source larshp/master and then I merge it.

2020-09-04 10:44 UTC, flaiker commented
Usually you don't create PRs on forks (unless they are hard forks living independently). I guess the PR creates a non fast forward merge commit which here shows up as new commit that should be merged.

I just do  
`git checkout master`  
`git fetch upstream`  
`git merge upstream/master master`  
`git push origin master`.

If you already have a feature branch you want to update I personally do a rebase but merging should work as well.

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

2020-09-04 10:48 UTC, g-back commented
Alterantively you can continue using the `pull` app - I sent you a DM in slack where I explain what you can change

2020-09-04 10:59 UTC, mariusraht2 commented
Alright guys, thank you very much for the input! :) I'll change it accordingly in future PRs.

2020-09-06 07:58 UTC, larshp requested changes
suggest being able to pass any(reasnable) number, there is no need to add restrictions(eg. passing 10 as deepen level wont work with N length 1), or adding extra TYPES

also see https://github.com/larshp/abapGit/pull/3835#discussion_r483032946

2020-09-06 08:35 UTC, mariusraht2 commented
What do you mean? Declaration is with N DEFAULT 1 not LENGTH - do I miss something here?

2020-09-09 07:10 UTC, mariusraht2 commented
@larshp Should be fine now - replaced N with I. Forgot that N has a default length of 1 because it's a num-like character.

2020-09-09 07:49 UTC, larshp approved these changes

2020-09-09 07:49 UTC, larshp commented
thanks 👍

2020-09-09 07:50 UTC, merged